2025-04-07 15:29:47,382 INFO    MainThread:1043179 [wandb_setup.py:_flush():67] Current SDK version is 0.19.9
2025-04-07 15:29:47,382 INFO    MainThread:1043179 [wandb_setup.py:_flush():67] Configure stats pid to 1043179
2025-04-07 15:29:47,382 INFO    MainThread:1043179 [wandb_setup.py:_flush():67] Loading settings from /home/nickadkins47/.config/wandb/settings
2025-04-07 15:29:47,382 INFO    MainThread:1043179 [wandb_setup.py:_flush():67] Loading settings from /home/nickadkins47/CS4900/CS4900-PA7/wandb/settings
2025-04-07 15:29:47,382 INFO    MainThread:1043179 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-04-07 15:29:47,382 INFO    MainThread:1043179 [wandb_init.py:setup_run_log_directory():662] Logging user logs to /home/nickadkins47/CS4900/CS4900-PA7/wandb/run-20250407_152947-3l82kylp/logs/debug.log
2025-04-07 15:29:47,382 INFO    MainThread:1043179 [wandb_init.py:setup_run_log_directory():663] Logging internal logs to /home/nickadkins47/CS4900/CS4900-PA7/wandb/run-20250407_152947-3l82kylp/logs/debug-internal.log
2025-04-07 15:29:47,383 INFO    MainThread:1043179 [wandb_init.py:init():781] calling init triggers
2025-04-07 15:29:47,383 INFO    MainThread:1043179 [wandb_init.py:init():786] wandb.init called with sweep_config: {}
config: {'env_name': 'Pendulum-v1', 'algorithm': 'SAC', 'policy_type': 'MlpPolicy', 'total_timesteps': 100000, '_wandb': {}}
2025-04-07 15:29:47,383 INFO    MainThread:1043179 [wandb_init.py:init():809] starting backend
2025-04-07 15:29:47,383 INFO    MainThread:1043179 [wandb_init.py:init():813] sending inform_init request
2025-04-07 15:29:47,386 INFO    MainThread:1043179 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-07 15:29:47,386 INFO    MainThread:1043179 [wandb_init.py:init():823] backend started and connected
2025-04-07 15:29:47,386 INFO    MainThread:1043179 [wandb_init.py:init():915] updated telemetry
2025-04-07 15:29:47,392 INFO    MainThread:1043179 [wandb_init.py:init():939] communicating run to backend with 90.0 second timeout
2025-04-07 15:29:47,870 INFO    MainThread:1043179 [wandb_init.py:init():1014] starting run threads in backend
2025-04-07 15:29:47,943 INFO    MainThread:1043179 [wandb_run.py:_console_start():2454] atexit reg
2025-04-07 15:29:47,943 INFO    MainThread:1043179 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-04-07 15:29:47,943 INFO    MainThread:1043179 [wandb_run.py:_redirect():2371] Wrapping output streams.
2025-04-07 15:29:47,943 INFO    MainThread:1043179 [wandb_run.py:_redirect():2394] Redirects installed.
2025-04-07 15:29:47,944 INFO    MainThread:1043179 [wandb_init.py:init():1056] run started, returning control to user process
2025-04-07 15:29:48,843 INFO    MainThread:1043179 [wandb_run.py:_tensorboard_callback():1524] tensorboard callback: models/3l82kylp/log/SAC_1, True
2025-04-07 15:29:48,849 INFO    MainThread:1043179 [wandb_watch.py:_watch():71] Watching
2025-04-07 15:29:48,850 INFO    MainThread:1043179 [wandb_run.py:_config_callback():1327] config_cb None None {'algo': 'SAC', 'policy_class': "<class 'stable_baselines3.sac.policies.SACPolicy'>", 'device': 'cpu', 'verbose': 1, 'policy_kwargs': "{'use_sde': False}", 'num_timesteps': 0, '_total_timesteps': 100000, '_num_timesteps_at_start': 0, 'seed': 'None', 'action_noise': 'None', 'start_time': 1744054188736917914, 'learning_rate': 0.0003, 'tensorboard_log': 'models/3l82kylp/log', '_last_obs': '[[ 0.67862165 -0.734488    0.9478008 ]]', '_last_episode_starts': '[ True]', '_last_original_obs': 'None', '_episode_num': 0, 'use_sde': 'False', 'sde_sample_freq': -1, '_current_progress_remaining': 1.0, '_stats_window_size': 100, 'ep_info_buffer': 'deque([], maxlen=100)', 'ep_success_buffer': 'deque([], maxlen=100)', '_n_updates': 0, '_custom_logger': 'False', 'env': '<stable_baselines3.common.vec_env.vec_video_recorder.VecVideoRecorder object at 0x7f8cc4c9f580>', '_vec_normalize_env': 'None', 'observation_space': 'Box([-1. -1. -8.], [1. 1. 8.], (3,), float32)', 'action_space': 'Box(-2.0, 2.0, (1,), float32)', 'n_envs': 1, 'buffer_size': 1000000, 'batch_size': 256, 'learning_starts': 100, 'tau': 0.005, 'gamma': 0.99, 'gradient_steps': 1, 'optimize_memory_usage': 'False', 'replay_buffer': '<stable_baselines3.common.buffers.ReplayBuffer object at 0x7f8cc4909e10>', 'replay_buffer_class': "<class 'stable_baselines3.common.buffers.ReplayBuffer'>", 'replay_buffer_kwargs': '{}', '_episode_storage': 'None', 'train_freq': "TrainFreq(frequency=1, unit=<TrainFrequencyUnit.STEP: 'step'>)", 'use_sde_at_warmup': 'False', 'target_entropy': -1.0, 'log_ent_coef': 'tensor([0.], requires_grad=True)', 'ent_coef': 'auto', 'target_update_interval': 1, 'ent_coef_optimizer': 'Adam (\nParameter Group 0\n    amsgrad: False\n    betas: (0.9, 0.999)\n    capturable: False\n    differentiable: False\n    eps: 1e-08\n    foreach: None\n    fused: None\n    lr: 0.0003\n    maximize: False\n    weight_decay: 0\n)', 'lr_schedule': '<function get_schedule_fn.<locals>.<lambda> at 0x7f8cbf7149d0>', 'policy': 'SACPolicy(\n  (actor): Actor(\n    (features_extractor): FlattenExtractor(\n      (flatten): Flatten(start_dim=1, end_dim=-1)\n    )\n    (latent_pi): Sequential(\n      (0): Linear(in_features=3, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=256, out_features=256, bias=True)\n      (3): ReLU()\n    )\n    (mu): Linear(in_features=256, out_features=1, bias=True)\n    (log_std): Linear(in_features=256, out_features=1, bias=True)\n  )\n  (critic): ContinuousCritic(\n    (features_extractor): FlattenExtractor(\n      (flatten): Flatten(start_dim=1, end_dim=-1)\n    )\n    (qf0): Sequential(\n      (0): Linear(in_features=4, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=256, out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256, out_features=1, bias=True)\n    )\n    (qf1): Sequential(\n      (0): Linear(in_features=4, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=256, out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256, out_features=1, bias=True)\n    )\n  )\n  (critic_target): ContinuousCritic(\n    (features_extractor): FlattenExtractor(\n      (flatten): Flatten(start_dim=1, end_dim=-1)\n    )\n    (qf0): Sequential(\n      (0): Linear(in_features=4, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=256, out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256, out_features=1, bias=True)\n    )\n    (qf1): Sequential(\n      (0): Linear(in_features=4, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=256, out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256, out_features=1, bias=True)\n    )\n  )\n)', 'actor': 'Actor(\n  (features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (latent_pi): Sequential(\n    (0): Linear(in_features=3, out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256, out_features=256, bias=True)\n    (3): ReLU()\n  )\n  (mu): Linear(in_features=256, out_features=1, bias=True)\n  (log_std): Linear(in_features=256, out_features=1, bias=True)\n)', 'critic': 'ContinuousCritic(\n  (features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=4, out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256, out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256, out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=4, out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256, out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256, out_features=1, bias=True)\n  )\n)', 'critic_target': 'ContinuousCritic(\n  (features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=4, out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256, out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256, out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=4, out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256, out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256, out_features=1, bias=True)\n  )\n)', 'batch_norm_stats': '[]', 'batch_norm_stats_target': '[]', '_logger': '<stable_baselines3.common.logger.Logger object at 0x7f8ca5dc2e00>'}
2025-04-07 16:08:47,270 INFO    MsgRouterThr:1043179 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-04-07 16:08:47,425 ERROR   Thread-5  :1043179 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-07 16:08:47,533 ERROR   Thread-5  :1043179 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-07 16:08:47,638 ERROR   Thread-5  :1043179 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-07 16:08:47,743 ERROR   Thread-5  :1043179 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-07 16:08:47,847 ERROR   Thread-5  :1043179 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-07 16:08:47,951 ERROR   Thread-5  :1043179 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
